# do not download any extra packages
language: generic

# only run builds from pushes to master
branches:
  only:
  - master

# only send emails when build status changes from success to broken
notifications:
  email:
    on_success: never
    on_failure: change

script:
- echo "hello world"
#- bash ./md-to-html.sh
#after_success:
#- bash ./deploy-gh-pages.sh
