language: generic
sudo: required
branches:
  only:
  - master
notifications:
  email:
    on_success: never
    on_failure: change
install:
- bash ./Scripts/install.sh
script:
- bash ./Scripts/md-to-html.sh
after_success:
- 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./Scripts/deploy-gh-pages.sh; fi'
env:
  global:
  - GH_REF="github.com/UVASGD/sgd-docs.git"
  - secure: RIu9Qgx1gK1dAihRJDrnQvbsBYFa4X2/OEatepiN+STeGaJLTpAvP8Hp9vT3bJZvsfdXfZi4cs6NRPOdBW9KjPD8SqzYuxEXHqWgMiBe7/BaQbsci56nqFz0nViuh1kmR6rk6C7CRgwCIOa0xw4oyCO8Qv16nzTzh80a48kCh8XQbFCr9LsziTJnn1HRX4nJbW7xloDMMMf4HySsDktr4uDk79YhVFF7slACR1vr+bk9OfFxbI/NrQNBCU7Lf8eVhD2WXVQFurZUSjNZV015mm6Ad4rtQD4D3y2LIe3hPtl02Q44PuqJXP8S2fu8wx6ZJhfjEtIlyzwgyyQ/kbIhzB2Op/Cu4Awt09aTbsujHZyv5t5Wb72XDCxDwkRt6Kp8NUmrS7yvOZdKu0HbFaqqMhnqM/Vsv3n/8W9oUkGL4eWtQqa4diVaocFFTMEqWahtA63ErP0wh1FFXl0icH594Fo3iTGB3SAvWHH+wbgFNG2nM2BDj24NkGpCQ4n3RKavxSreYXxYZ8Trdb+PinzRzYIlo5oT04G3eq60tf2ZGGodHE2daRNkGdfp0VdekR1wBnp+hhZ0B2b9hVrnGhvtlDKYuAa9UlDQzfKirJRhQPdwST4nWHh+nenw0waOjmUrr4zIYfJrr3BHCeOtvS9zULd95l1N2OzCa3BFhQhZmEk=
