name: Pandoc + Deploy Site
on:
  push:
    branches: [ "master" ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v7
        with:
          ref: master

      - name: Install Pandoc
        run: bash ./Scripts/install.sh

      - name: Convert Markdown to HTML
        run: bash ./Scripts/md-to-html.sh

      - name: Push to gh_pages branch
        run: bash ./Scripts/deploy-gh-pages.sh
        env:
          GH_REF: ${{secrets.GH_REF}}
          GH_TOKEN: ${{secrets.GH_TOKEN}}
