name: Pandoc + Deploy Site
on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v7
        with:
          ref: master

      - name: Install Pandoc
        run: bash ./Scripts/install.sh

      - name: Convert Markdown to HTML
        run: bash ./Scripts/md-to-html.sh

#      - name: Push to gh_pages branch
#        run: bash ./Scripts/deploy-gh-pages.sh
#        env:
#          GH_REF: ${{secrets.GH_REF}}
#          GH_TOKEN: ${{secrets.GH_TOKEN}}

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1

      - name: Upload HTML Artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
